version: '3.2'

services:
    db:
        build:
            context: .
            dockerfile: ./compose/mysql/Dockerfile
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
        volumes:
            - ./data/db:/var/lib/mysql
            - ./data/scripts:/docker-entrypoint-initdb.d/:ro
        ports:
            - "3307:3306"
    adminer:
        image: adminer:4.3.1
        ports:
            - "8080:8080"
